### ISSUE TITLE
Does not work on Netgear poe 48 port switch

### ISSUE THREAD

**Issue by KhurramFHassan** [PitWenkin/check_switch#11]
The script does not work when I try to check the number of up ports on a 48 port Netgear switch. The command line I am using is
`check_switch -h <ip> -c <community> -n 48 -o u -s ports`

 It gives the following error:
`Error in packet
Reason: (tooBig) Response message would have been too large.
CRITICAL - Problem with SNMP request, check user/password/host`

In fact, any number greater than equal to 40 with -n gives the above error. If I use 39 or less, the script works.

Khurram

**Comment by PitWenkin** [comment]
Strange, I can go as high as 58 on a 88 ports Netgear switch before I get that message. (I never tried this until now)

At 64 I get a totally different message `Too many object identifiers specified. Only 128 allowed in one request.`

For Lancom I get a normal answer for a 52 ports, if I request all 52 ports.

I'll try to fix this, but I think this is a limit of the protocol.

**Comment by KhurramFHassan** [comment]
The error is thrown by the snmpget command on line 215 in the script. Maybe it is system specific (my system is running Ubuntu 20.04 x64). I have made some changes in your script to handle 48 ports but it is definitely hackish :) If you want, I can send it to you.

**Comment by PitWenkin** [comment]
Are you able to do a pull request? (I don't know where I could check if it's allowed or not)

For each port I request the current status as well as the time since the last status change. This is why there are double the amount of OID's requested as the are ports request. There for the request or the answer hit a size limit.

Adding an option to omit the time in favour of more ports could be an options …

**Comment by KhurramFHassan** [comment]
I am not able to authenticate using git-pull-request. I must confess I don't know much about git. I can send you a diff if it will help.

**Comment by PitWenkin** [comment]
You should be able to send files as attachements to these comments :)

**Comment by KhurramFHassan** [comment]
Here's the modified script. The only changes are in the "ports" section. Its somewhat kludgy though :)
[check_switch.zip](https://github.com/PitWenkin/check_switch/files/9622736/check_switch.zip)

**Comment by PitWenkin** [comment]
I don't think I'll find time the next few days for this. Feel free to remind me to take a look at it if I have not responded after two weeks

**Comment by KhurramFHassan** [comment]
Any update?

**Comment by PitWenkin** [comment]
> Any update?

Sorry initially I was a bit confused with the indentation differences, and afterwards I totally forgot to look into it.
I have now integrated your changes into to code, via #12 but still need to check if the logic is ok and if it fixes the problem.

I'll do this soon (definitely this year 😉)

**Comment by PitWenkin** [comment]
@KhurramFHassan as far as I understand your code, you are basically doing multiple snmp requests, consisting of current state and time since last change for each port.

After removing the double for-loop and some testing I can confirm that this works on a 88 port Netgear switch.

You even introduced a check for some ports that might not work as intended. Incase of the 88 port switch the ports seem to be 1-44 & 49-92  with 45-48 being intern post not accessible via snmp.

I will test it a bit before merging, but I think it's ok
